% Generated by STEP2MDH using Craig modified-DH convention.
% Requires Peter Corke Robotics Toolbox for MATLAB.
% Source STEP: 0A-自定义控制器.STEP
% 3 internal virtual frame(s) are absorbed into MDH constants/base/tool.

clear L;
% q(1) -> Joint 1 [revolute]
L(1) = Link([0, 0, 0, 0, 0, 0], 'modified');
% q(2) -> Joint 2 [revolute]
L(2) = Link([0, 3.46944695195e-17, 0.0000110681833219, 1.57079632679, 0, -1.44453234622e-8], 'modified');
% q(3) -> Joint 3 [revolute]
L(3) = Link([0, -0.00112835422632, 0.115000001715, -9.27297201908e-23, 0, 1.57079634125], 'modified');
% q(4) -> Joint 4 [revolute]
L(4) = Link([0, 0.132499995747, 6.00062055600e-10, 1.57079632679, 0, 1.57079632679], 'modified');
% q(5) -> Joint 5 [revolute]
L(5) = Link([0, 0.000199999035987, 0.000166025399724, 1.57079632679, 0, 5.20048286518e-30], 'modified');
% q(6) -> Joint 6 [revolute]
L(6) = Link([0, 0.0914999954125, 0.000168740102923, -1.57079632679, 0, 0], 'modified');

robot = SerialLink(L, 'name', '0A-自定义控制器');
robot.base = [-2.37754048683e-16, 4.75508097365e-16, -1, -0.145600001325; 7.37037550916e-15, -1, -4.75508097365e-16, -0.046256410095; -1, -7.37037550916e-15, 2.37754048683e-16, -0.0249889315516; 0, 0, 0, 1];
robot.tool = [1, 0, 0, 0; 0, 1, 0, 0; 0, 0, 1, 0; 0, 0, 0, 1];
