% Generated by STEP2MDH using Craig modified-DH convention.
% Requires Peter Corke Robotics Toolbox for MATLAB.
% Source STEP: 0A-自定义控制器.STEP
% 2 internal virtual frame(s) are absorbed into MDH constants/base/tool.

clear L;
% q(1) -> Joint 1 [revolute]
L(1) = Link([0, 0, 0, 0, 0, 0], 'modified');
% q(2) -> Joint 2 [revolute]
L(2) = Link([0, -3.46944695195e-17, 0.0000110683396203, -1.57079632679, 0, -0.0128626689988], 'modified');
% q(3) -> Joint 3 [revolute]
L(3) = Link([0, -0.00114117225261, 0.115009513345, -8.86839518269e-17, 0, 1.58365899579], 'modified');
% q(4) -> Joint 4 [revolute]
L(4) = Link([0, 0.133590850823, 0.00147928681154, 1.57079632679, 0, 1.57079632679], 'modified');
% q(5) -> Joint 5 [revolute]
L(5) = Link([0, 0.000199997088441, 0.000134764269807, -1.57079632679, 0, -1.18877024341e-15], 'modified');
% q(6) -> Joint 6 [revolute]
L(6) = Link([0, 0.0904091426363, 0.000200000881001, 1.57079632679, 0, 0], 'modified');

robot = SerialLink(L, 'name', '0A-自定义控制器');
robot.base = [2.37754048683e-16, -4.75508097365e-16, 1, 0.095600000148; 6.89486741180e-15, 1, 4.75508097365e-16, -0.0462435921191; -1, 6.89486741180e-15, 2.37754048683e-16, -0.0249889313953; 0, 0, 0, 1];
robot.tool = [1, 0, 0, 0; 0, 1, 0, 0; 0, 0, 1, 0; 0, 0, 0, 1];
